# Alacritty Configuration
# Based on your Ghostty and tmux preferences

[general]
# Import additional configuration files
import = []

# Live config reload (changes reload automatically)
live_config_reload = true

# Working directory
working_directory = "None"

[window]
# Window dimensions (in columns and lines)
dimensions = { columns = 100, lines = 30 }

# Window padding (in pixels)
padding = { x = 2, y = 2 }

# Window decorations
decorations = "Full"

# Opacity (matching your terminal setup)
opacity = 1.0

# Startup mode
startup_mode = "Windowed"

# Window title
title = "Alacritty"

# Dynamic title
dynamic_title = true

[scrolling]
# Maximum lines in scrollback buffer
history = 10000

# Scrolling multiplier
multiplier = 3

[font]
# Font configuration (matching your Ghostty config)
normal = { family = "Cascadia Code NF", style = "Regular" }
bold = { family = "Cascadia Code NF", style = "Bold" }
italic = { family = "Cascadia Code NF", style = "SemiBold Italic" }
bold_italic = { family = "Cascadia Code NF", style = "Bold Italic" }

# Font size (matching your Ghostty config)
size = 12.0

# Offset for character spacing
offset = { x = 0, y = 0 }

# Glyph offset
glyph_offset = { x = 0, y = 0 }

# Use thin strokes for fonts
builtin_box_drawing = true

[colors]
# Using Catppuccin Mocha theme (matching your Ghostty theme)
primary = { background = "#1e1e2e", foreground = "#cdd6f4" }

# Tab bar colors (dark theme)
hints = { start = { foreground = "#1e1e2e", background = "#f9e2af" }, end = { foreground = "#1e1e2e", background = "#89b4fa" } }
footer_bar = { background = "#11111b", foreground = "#cdd6f4" }

# Cursor colors
cursor = { text = "#1e1e2e", cursor = "#f5e0dc" }

# Vi mode cursor colors
vi_mode_cursor = { text = "#1e1e2e", cursor = "#b4befe" }

# Selection colors
selection = { text = "#1e1e2e", background = "#f5e0dc" }

# Search colors
search = { matches = { foreground = "#1e1e2e", background = "#a6adc8" }, focused_match = { foreground = "#1e1e2e", background = "#a6e3a1" } }

# Normal colors
normal = { black = "#45475a", red = "#f38ba8", green = "#a6e3a1", yellow = "#f9e2af", blue = "#89b4fa", magenta = "#f5c2e7", cyan = "#94e2d5", white = "#bac2de" }

# Bright colors
bright = { black = "#585b70", red = "#f38ba8", green = "#a6e3a1", yellow = "#f9e2af", blue = "#89b4fa", magenta = "#f5c2e7", cyan = "#94e2d5", white = "#a6adc8" }

# Indexed colors
indexed_colors = []

[bell]
# Visual bell animation
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

# Command to run when bell rings
command = "None"

[cursor]
# Cursor style
style = { shape = "Block", blinking = "Off" }

# Vi mode cursor style
vi_mode_style = "None"

# Cursor blinking interval
blink_interval = 750

# Unfocused hollow cursor
unfocused_hollow = true

# Thickness of the cursor
thickness = 0.15

[terminal]
# Shell configuration
shell = { program = "/bin/zsh" }

# Enable OSC 52 for clipboard support
osc52 = "OnlyCopy"

[mouse]
# Hide mouse cursor when typing (matching your Ghostty config)
hide_when_typing = true

# Mouse bindings
bindings = []

[keyboard]
# Key bindings (based on your Ghostty and tmux configs)
bindings = [
  # macOS specific bindings
  { key = "N", mods = "Command", action = "CreateNewWindow" },
  { key = "W", mods = "Command", action = "Quit" },
  { key = "Q", mods = "Command", action = "Quit" },
  { key = "F", mods = "Command|Control", action = "ToggleFullscreen" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "H", mods = "Command", action = "Hide" },
  { key = "M", mods = "Command", action = "Minimize" },
  
  # Tab navigation (matching your Ghostty keybinds)
  { key = "T", mods = "Command", action = "CreateNewTab" },
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
  { key = "LBracket", mods = "Control|Command", action = "SelectPreviousTab" },
  { key = "RBracket", mods = "Control|Command", action = "SelectNextTab" },
  { key = "Key1", mods = "Command", action = "SelectTab1" },
  { key = "Key2", mods = "Command", action = "SelectTab2" },
  { key = "Key3", mods = "Command", action = "SelectTab3" },
  { key = "Key4", mods = "Command", action = "SelectTab4" },
  { key = "Key5", mods = "Command", action = "SelectTab5" },
  { key = "Key6", mods = "Command", action = "SelectTab6" },
  { key = "Key7", mods = "Command", action = "SelectTab7" },
  { key = "Key8", mods = "Command", action = "SelectTab8" },
  { key = "Key9", mods = "Command", action = "SelectLastTab" },
  
  # Font size adjustments
  { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Command", action = "ResetFontSize" },
  
  # Scrolling
  { key = "K", mods = "Command", action = "ClearHistory" },
  { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollPageDown" },
  { key = "Home", mods = "Shift", mode = "~Alt", action = "ScrollToTop" },
  { key = "End", mods = "Shift", mode = "~Alt", action = "ScrollToBottom" },
  
  # Shift+Enter to send newline (matching your Ghostty and tmux behavior)
  { key = "Return", mods = "Shift", chars = "\n" },
  
  # Vi Mode
  { key = "Space", mods = "Control|Shift", mode = "~Search", action = "ToggleViMode" },
  { key = "Escape", mode = "Vi|~Search", action = "ClearSelection" },
  { key = "I", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "C", mods = "Control", mode = "Vi|~Search", action = "ToggleViMode" },
]

[selection]
# Selection semantic escape characters
semantic_escape_chars = ",|`|:\"' ()[]{}<>\\t"

# Save selected text to clipboard
save_to_clipboard = true

[debug]
# Log level
log_level = "Warn"

# Print all received window events
print_events = false

# Renderer
renderer = "None"

# Highlight damage information
highlight_damage = false

# Prefer EGL over GLX (Linux/BSD only)
prefer_egl = false

# Force renderer fallback
force_fallback_renderer = false