# Starship configuration
# Documentation: https://starship.rs/config/

# Format configuration to prevent extra newlines
format = "$all$character"
right_format = ""
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false