source $HOME/.profile

# Path to your oh-my-zsh installation.
# export TERM="xterm-256color"
export TERM="xterm-new"
export ZSH="/Users/pranavsingh/.oh-my-zsh"
export BUNDLER_EDITOR=nvim

ZSH_THEME="robbyrussell"

# export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_DEFAULT_OPTS='--height 60% --reverse --border'

plugins=(
  rails
  git
)

source $ZSH/oh-my-zsh.sh
# Sourcing rupa/z
. $HOME/z/z.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export INTERCOM_USER=pranav.singh
eval "$(rbenv init -)"
export PATH=$HOME/.pilot/bin:$PATH
eval $(pilot env)

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
source /Users/pranavsingh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export AWS_DEFAULT_REGION="us-east-1"
